In [46]:
import pandas as pd
import numpy as np
import seaborn as sns

In [47]:
df = pd.read_excel(r'C:Downloads\Dataset.xlsx')

In [48]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [49]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [50]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [51]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

#Find Missig Vlaues

In [53]:
df.drop("CouponCode", axis=1, inplace=True)

In [54]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
ReferralSource     0
TotalPrice         0
dtype: int64

# data reduction

In [58]:
df.drop(["TrackingNumber", "OrderID","CustomerID","ShippingAddress"], axis=1, inplace=True)

In [60]:
df.isnull().sum()

Date              0
Product           0
Quantity          0
UnitPrice         0
PaymentMethod     0
OrderStatus       0
ItemsInCart       0
ReferralSource    0
TotalPrice        0
dtype: int64

# Transformation

In [68]:
df['Date'] = pd.to_datetime(df['Date'])

In [69]:
df.isnull().sum()

Date              0
Product           0
Quantity          0
UnitPrice         0
PaymentMethod     0
OrderStatus       0
ItemsInCart       0
ReferralSource    0
TotalPrice        0
dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1200 non-null   datetime64[ns]
 1   Product         1200 non-null   category
 2   Quantity        1200 non-null   int64
 3   UnitPrice       1200 non-null   float64
 4   PaymentMethod   1200 non-null   category
 5   OrderStatus     1200 non-null   category
 6   ItemsInCart     1200 non-null   int64
 7   ReferralSource  1200 non-null   category
 8   TotalPrice      1200 non-null   float64
dtypes: category(4), datetime64[ns](1), float64(2), int64(2)
memory usage: 52.7 KB

In [70]:
df['Product'] = df['Product'].astype('category')

In [71]:
df['PaymentMethod'] = df['PaymentMethod'].astype('category')
df['OrderStatus'] = df['OrderStatus'].astype('category')
df['ReferralSource'] = df['ReferralSource'].astype('category')

In [76]:
df['Quantity'] = df['Quantity'].astype(int)
df['UnitPrice'] = df['UnitPrice'].astype(float)
df['ItemsInCart'] = df['ItemsInCart'].astype(int)
df['TotalPrice'] = df['TotalPrice'].astype(float)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1200 non-null   datetime64[ns]
 1   Product         1200 non-null   category
 2   Quantity        1200 non-null   int64
 3   UnitPrice       1200 non-null   float64
 4   PaymentMethod   1200 non-null   category
 5   OrderStatus     1200 non-null   category
 6   ItemsInCart     1200 non-null   int64
 7   ReferralSource  1200 non-null   category
 8   TotalPrice      1200 non-null   float64
dtypes: category(4), datetime64[ns](1), float64(2), int64(2)
memory usage: 52.7 KB

In [78]:
df.duplicated().sum()

np.int64(0)